import { PlanConfig, PlanType } from './types';

export const PLANS: Record<PlanType, PlanConfig> = {
  gratis: {
    id: 'gratis',
    name: 'Gratis',
    price: 0,
    period: 'para siempre',
    description: 'Perfecto para empezar. Crea tu primera tarjeta digital con QR.',
    maxCards: 1,
    storage: 50,
    hasWebCard: false,
    hasWatermark: true,
    qrExpires: true,
    qrExpirationDays: 7,
    highlight: false,
    features: [
      { name: '1 tarjeta virtual', included: true },
      { name: 'Foto de perfil', included: true },
      { name: 'Nombre y teléfono', included: true },
      { name: 'Descripción breve', included: true },
      { name: 'Código QR con vencimiento (7 días)', included: true },
      { name: 'QR redirige a WhatsApp', included: true },
      { name: 'Mensaje de WhatsApp personalizable', included: true },
      { name: 'Imagen descargable con marca de agua', included: true },
      { name: 'Verificación de número WhatsApp', included: true },
      { name: 'Tarjeta web compartible', included: false },
      { name: 'Servicios y productos', included: false },
      { name: 'Galería de imágenes', included: false },
      { name: 'Portafolio / Blog', included: false },
      { name: 'Testimonios', included: false },
      { name: 'Equipo y citas', included: false },
      { name: 'Enlaces sociales', included: false },
      { name: 'Feed de Instagram', included: false },
      { name: 'Marcos flotantes', included: false },
      { name: 'Tarjeta virtual dinámica', included: false },
      { name: 'Personalizar código QR', included: false },
      { name: 'Plantillas premium', included: false },
      { name: 'CSS y JS personalizado', included: false },
      { name: 'Fuentes personalizadas', included: false },
      { name: 'Ocultar marca FTP', included: false },
      { name: 'Analítica avanzada', included: false },
      { name: 'SEO optimizado', included: false },
      { name: 'Enlaces personalizados', included: false },
      { name: 'Sin marca de agua', included: false },
      { name: 'Protección de contraseña', included: false },
      { name: 'Afiliación', included: false },
      { name: 'Soporte prioritario', included: false },
    ],
  },
  basico: {
    id: 'basico',
    name: 'Básico',
    price: 199,
    period: 'pago único',
    description: 'Para profesionales que necesitan una presencia digital completa.',
    maxCards: 2,
    storage: 200,
    hasWebCard: true,
    hasWatermark: false,
    qrExpires: false,
    qrExpirationDays: 0,
    highlight: true,
    badge: 'Más popular',
    features: [
      { name: '2 tarjetas virtuales', included: true },
      { name: 'Foto de perfil', included: true },
      { name: 'Nombre y teléfono', included: true },
      { name: 'Descripción breve', included: true },
      { name: 'Código QR permanente (sin vencimiento)', included: true },
      { name: 'QR redirige a WhatsApp', included: true },
      { name: 'Mensaje de WhatsApp personalizable', included: true },
      { name: 'Imagen descargable sin marca de agua', included: true },
      { name: 'Verificación de número WhatsApp', included: true },
      { name: 'Tarjeta web compartible', included: true },
      { name: 'Servicios y productos', included: true },
      { name: 'Galería de imágenes', included: true },
      { name: 'Portafolio / Blog', included: true },
      { name: 'Testimonios', included: true },
      { name: 'Equipo y citas', included: true },
      { name: 'Enlaces sociales', included: true },
      { name: 'Feed de Instagram', included: true },
      { name: 'Marcos flotantes', included: true },
      { name: 'Tarjeta virtual dinámica', included: true },
      { name: 'Personalizar código QR', included: true },
      { name: 'Plantillas premium', included: true },
      { name: 'CSS y JS personalizado', included: true },
      { name: 'Fuentes personalizadas', included: true },
      { name: 'Ocultar marca FTP', included: true },
      { name: 'Analítica básica', included: true },
      { name: 'SEO optimizado', included: true },
      { name: 'Enlaces personalizados', included: false },
      { name: 'Sin marca de agua', included: true },
      { name: 'Protección de contraseña', included: true },
      { name: 'Afiliación', included: true },
      { name: 'Soporte por correo', included: true },
    ],
  },
  pro: {
    id: 'pro',
    name: 'Pro',
    price: 500,
    period: 'por año',
    description: 'Para empresas que necesitan el máximo potencial digital.',
    maxCards: 5,
    storage: 2000,
    hasWebCard: true,
    hasWatermark: false,
    qrExpires: false,
    qrExpirationDays: 0,
    highlight: false,
    badge: 'Máximo potencial',
    features: [
      { name: '5 tarjetas virtuales', included: true },
      { name: 'Foto de perfil', included: true },
      { name: 'Nombre y teléfono', included: true },
      { name: 'Descripción breve', included: true },
      { name: 'Código QR permanente (sin vencimiento)', included: true },
      { name: 'QR redirige a WhatsApp', included: true },
      { name: 'Mensaje de WhatsApp personalizable', included: true },
      { name: 'Imagen descargable sin marca de agua', included: true },
      { name: 'Verificación de número WhatsApp', included: true },
      { name: 'Tarjeta web compartible', included: true },
      { name: 'Servicios y productos', included: true },
      { name: 'Galería de imágenes ilimitada', included: true },
      { name: 'Portafolio / Blog avanzado', included: true },
      { name: 'Testimonios con calificación', included: true },
      { name: 'Equipo y citas con pagos', included: true },
      { name: 'Enlaces sociales ilimitados', included: true },
      { name: 'Feed de Instagram en vivo', included: true },
      { name: 'Marcos flotantes ilimitados', included: true },
      { name: 'Tarjeta virtual dinámica premium', included: true },
      { name: 'Personalizar código QR avanzado', included: true },
      { name: 'Plantillas premium exclusivas', included: true },
      { name: 'CSS y JS personalizado', included: true },
      { name: 'Fuentes personalizadas premium', included: true },
      { name: 'Ocultar marca FTP', included: true },
      { name: 'Analítica avanzada con gráficas', included: true },
      { name: 'SEO optimizado + meta tags', included: true },
      { name: 'Enlaces personalizados', included: true },
      { name: 'Sin marca de agua', included: true },
      { name: 'Protección de contraseña', included: true },
      { name: 'Programa de afiliación premium', included: true },
      { name: 'Soporte prioritario 24/7', included: true },
    ],
  },
};

export const PLAN_ORDER: PlanType[] = ['gratis', 'basico', 'pro'];

export const TEMPLATES = [
  { id: 'moderno', name: 'Moderno', description: 'Diseño limpio con gradientes' },
  { id: 'clasico', name: 'Clásico', description: 'Elegante atemporal' },
  { id: 'minimalista', name: 'Minimalista', description: 'Solo lo esencial' },
  { id: 'elegante', name: 'Elegante', description: 'Tipografía serif sofisticada' },
  { id: 'dinamica', name: 'Dinámica', description: 'Animaciones y efectos visuales' },
] as const;

export const FONTS = [
  { id: 'poppins', name: 'Poppins', css: "'Poppins', sans-serif" },
  { id: 'inter', name: 'Inter', css: "'Inter', sans-serif" },
  { id: 'roboto', name: 'Roboto', css: "'Roboto', sans-serif" },
  { id: 'montserrat', name: 'Montserrat', css: "'Montserrat', sans-serif" },
  { id: 'playfair', name: 'Playfair Display', css: "'Playfair Display', serif" },
  { id: 'lora', name: 'Lora', css: "'Lora', serif" },
  { id: 'oswald', name: 'Oswald', css: "'Oswald', sans-serif" },
  { id: 'raleway', name: 'Raleway', css: "'Raleway', sans-serif" },
];

export const COLOR_PRESETS = [
  { name: 'Esmeralda', primary: '#059669', secondary: '#10b981', background: '#ffffff', text: '#0f172a' },
  { name: 'Oro', primary: '#d97706', secondary: '#f59e0b', background: '#fffbeb', text: '#1c1917' },
  { name: 'Corinto', primary: '#be123c', secondary: '#f43f5e', background: '#fff1f2', text: '#1c1917' },
  { name: 'Púrpura', primary: '#7c3aed', secondary: '#a78bfa', background: '#faf5ff', text: '#1c1917' },
  { name: 'Cian', primary: '#0891b2', secondary: '#06b6d4', background: '#ecfeff', text: '#0f172a' },
  { name: 'Naranja', primary: '#ea580c', secondary: '#fb923c', background: '#fff7ed', text: '#1c1917' },
  { name: 'Esmeralda Oscuro', primary: '#064e3b', secondary: '#047857', background: '#f0fdf4', text: '#0f172a' },
  { name: 'Grafito', primary: '#1f2937', secondary: '#4b5563', background: '#f9fafb', text: '#111827' },
];

// Las 24 secciones del manual de edición
export const EDITOR_SECTIONS = [
  { id: 'detalles', name: 'Detalles Básicos', icon: 'User', description: 'Nombre, descripción, logo y portada' },
  { id: 'plantillas', name: 'Plantillas', icon: 'Layout', description: 'Elegir diseño de la tarjeta' },
  { id: 'dinamica', name: 'Tarjeta Dinámica', icon: 'Sparkles', description: 'Apariencia dinámica de la tarjeta' },
  { id: 'horario', name: 'Horario de Atención', icon: 'Clock', description: 'Configurar horario de la empresa' },
  { id: 'qr', name: 'Personalizar QR', icon: 'QrCode', description: 'Forma y apariencia del código QR' },
  { id: 'servicios', name: 'Servicios', icon: 'Briefcase', description: 'Agregar servicios que ofreces' },
  { id: 'productos', name: 'Productos', icon: 'ShoppingBag', description: 'Catálogo de productos' },
  { id: 'instagram', name: 'Feed de Instagram', icon: 'Instagram', description: 'Incrustar feed de Instagram' },
  { id: 'galeria', name: 'Galería', icon: 'Images', description: 'Galería de imágenes y videos' },
  { id: 'blog', name: 'Blog', icon: 'FileText', description: 'Artículos y publicaciones' },
  { id: 'testimonios', name: 'Testimonios', icon: 'Quote', description: 'Opiniones de clientes' },
  { id: 'marcos', name: 'Marcos Flotantes', icon: 'Frame', description: 'Ventanas a webs externas' },
  { id: 'equipo', name: 'Equipo y Citas', icon: 'Users', description: 'Configurar equipo y citas' },
  { id: 'sociales', name: 'Enlaces Sociales', icon: 'Share2', description: 'Redes sociales' },
  { id: 'bandera', name: 'Bandera / Anuncio', icon: 'Flag', description: 'Ventana emergente publicitaria' },
  { id: 'fuentes', name: 'Fuentes', icon: 'Type', description: 'Cambiar fuente y tamaño' },
  { id: 'avanzado', name: 'Avanzado (CSS/JS)', icon: 'Code', description: 'Código personalizado' },
  { id: 'motores', name: 'Motores de Búsqueda (SEO)', icon: 'Search', description: 'SEO y meta tags' },
  { id: 'privacidad', name: 'Políticas de Privacidad', icon: 'Shield', description: 'Políticas de privacidad' },
  { id: 'terminos', name: 'Términos y Condiciones', icon: 'ScrollText', description: 'Términos legales' },
  { id: 'secciones', name: 'Administrar Secciones', icon: 'Settings', description: 'Activar/desactivar módulos' },
  { id: 'whatsapp', name: 'Configuración WhatsApp', icon: 'MessageCircle', description: 'Número y mensaje de WhatsApp' },
  { id: 'fondos', name: 'Fondos Virtuales NFC', icon: 'CreditCard', description: 'Imágenes para tarjetas NFC' },
  { id: 'pagos', name: 'Métodos de Pago', icon: 'CreditCard', description: 'Configurar métodos de pago' },
] as const;

// Secciones del panel principal (Manual 1)
export const DASHBOARD_SECTIONS = [
  { id: 'tablero', name: 'Tablero', icon: 'LayoutDashboard', description: 'Vista general de tus tarjetas' },
  { id: 'compare', name: 'Comparar', icon: 'GitCompare', description: 'Compara tus tarjetas' },
  { id: 'stats', name: 'Analítica', icon: 'Search', description: 'Estadísticas y métricas de tus tarjetas' },
  { id: 'template-gallery', name: 'Plantillas', icon: 'Layout', description: 'Galería de plantillas disponibles' },
  { id: 'messages', name: 'Consultas', icon: 'Mail', description: 'Mensajes del formulario de contacto' },
  { id: 'appointments', name: 'Equipo / Citas', icon: 'Calendar', description: 'Citas agendadas' },
  { id: 'orders', name: 'Pedidos', icon: 'Package', description: 'Solicitudes de productos' },
  { id: 'virtual-funds', name: 'Fondos Virtuales', icon: 'CreditCard', description: 'Imágenes para tarjetas NFC' },
  { id: 'affiliations', name: 'Afiliaciones', icon: 'Users', description: 'Programa de afiliados' },
  { id: 'storage', name: 'Almacenamiento', icon: 'Database', description: 'Capacidad de almacenamiento' },
  { id: 'settings', name: 'Ajustes / Pagos', icon: 'Settings', description: 'Métodos de pago y configuración' },
  { id: 'help', name: 'Ayuda', icon: 'LifeBuoy', description: 'Centro de ayuda y soporte' },
] as const;
